print("fuck this shit")
print("im out")
print("im out")
print("im out")
print("im out")
print("im out")
print("im out")
print("im out")
print("im out")
print("im out")
print("im lama abada yatathanaa")
print("amaaanaanmanaamanananamamnamnaa")
print("memoire is nasty yall ")
print("all my time is wasted on it lol  ")
print("B day is tommorow AAAAAAAAAA ")
