print("fuck this shit")
print("im out")
print("im out")
print("im out")
print("im out")
print("im out")
print("im out")
print("im out")
print("im out")
print("im out")
print("im lama abada yatathanaa")
print("amaaanaanmanaamanananamamnamnaa")
